// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravModel.Infrastructure;

#nullable disable

namespace TravModel.Infrastructure.Migrations
{
    [DbContext(typeof(TravDbContext))]
    [Migration("20260912151302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravModel.Domain.BettingMarketMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LegNumber")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "Product", "ProductId")
                        .IsUnique();

                    b.ToTable("BettingMarketMemberships");
                });

            modelBuilder.Entity("TravModel.Domain.HistoricalStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalRaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("int");

                    b.Property<bool>("Galloped")
                        .HasColumnType("bit");

                    b.Property<Guid>("HorseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("KilometerTimeSeconds")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("Odds")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("PostPosition")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrizeMoneySek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RaceComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Shoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartMethod")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sulky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("HorseId", "ExternalRaceId")
                        .IsUnique();

                    b.ToTable("HistoricalStarts");
                });

            modelBuilder.Entity("TravModel.Domain.Horse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("TravModel.Domain.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("int");

                    b.Property<int>("RecordsWritten")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("TravModel.Domain.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("TravModel.Domain.ModelEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BrierScore")
                        .HasColumnType("float");

                    b.Property<double>("CalibrationError")
                        .HasColumnType("float");

                    b.Property<double>("Coverage")
                        .HasColumnType("float");

                    b.Property<double?>("FlatStakeRoi")
                        .HasColumnType("float");

                    b.Property<double>("LogLoss")
                        .HasColumnType("float");

                    b.Property<double?>("LogLossImprovementLower95")
                        .HasColumnType("float");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RaceCount")
                        .HasColumnType("int");

                    b.Property<double>("TopOneAccuracy")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId");

                    b.ToTable("ModelEvaluations");
                });

            modelBuilder.Entity("TravModel.Domain.ModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("TrainedThroughUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TrainingDatasetFingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("TravModel.Domain.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAuthoritative")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("EntityType", "EntityId", "Field", "RetrievedAtUtc");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("TravModel.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("TravModel.Domain.PredictionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DatasetFingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FeatureCutoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("RaceId", "ModelVersionId", "FeatureCutoffUtc")
                        .IsUnique();

                    b.ToTable("PredictionRuns");
                });

            modelBuilder.Entity("TravModel.Domain.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("int");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StartMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("TravModel.Domain.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FinishCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("int");

                    b.Property<bool>("Galloped")
                        .HasColumnType("bit");

                    b.Property<decimal?>("KilometerTimeSeconds")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PrizeMoneySek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RaceComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StarterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WinningMarginMetres")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("StarterId");

                    b.HasIndex("RaceId", "StarterId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TravModel.Domain.RawArtifactManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngestionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId", "Sha256")
                        .IsUnique();

                    b.ToTable("RawArtifactManifests");
                });

            modelBuilder.Entity("TravModel.Domain.Starter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HorseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HorseNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsScratched")
                        .HasColumnType("bit");

                    b.Property<int>("PostPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("HorseId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("RaceId", "HorseId")
                        .IsUnique();

                    b.ToTable("Starters");
                });

            modelBuilder.Entity("TravModel.Domain.StarterPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MarketOdds")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<Guid>("PredictionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("StarterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WinProbability")
                        .HasColumnType("float");

                    b.Property<bool?>("Won")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StarterId");

                    b.HasIndex("PredictionRunId", "StarterId")
                        .IsUnique();

                    b.ToTable("StarterPredictions");
                });

            modelBuilder.Entity("TravModel.Domain.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CircumferenceMetres")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("HasOpenStretch")
                        .HasColumnType("bit");

                    b.Property<int?>("HomestretchLengthMetres")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WidthMetres")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("TravModel.Domain.BettingMarketMembership", b =>
                {
                    b.HasOne("TravModel.Domain.Race", "Race")
                        .WithMany("BettingMarkets")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("TravModel.Domain.HistoricalStart", b =>
                {
                    b.HasOne("TravModel.Domain.Person", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravModel.Domain.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Person", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Horse");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TravModel.Domain.Meeting", b =>
                {
                    b.HasOne("TravModel.Domain.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("TravModel.Domain.ModelEvaluation", b =>
                {
                    b.HasOne("TravModel.Domain.ModelVersion", "ModelVersion")
                        .WithMany()
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("TravModel.Domain.PredictionRun", b =>
                {
                    b.HasOne("TravModel.Domain.ModelVersion", "ModelVersion")
                        .WithMany()
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelVersion");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("TravModel.Domain.Race", b =>
                {
                    b.HasOne("TravModel.Domain.Meeting", "Meeting")
                        .WithMany("Races")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("TravModel.Domain.RaceResult", b =>
                {
                    b.HasOne("TravModel.Domain.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Starter", "Starter")
                        .WithMany()
                        .HasForeignKey("StarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Starter");
                });

            modelBuilder.Entity("TravModel.Domain.RawArtifactManifest", b =>
                {
                    b.HasOne("TravModel.Domain.IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("TravModel.Domain.Starter", b =>
                {
                    b.HasOne("TravModel.Domain.Person", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Race", "Race")
                        .WithMany("Starters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Person", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Horse");

                    b.Navigation("Race");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TravModel.Domain.StarterPrediction", b =>
                {
                    b.HasOne("TravModel.Domain.PredictionRun", "PredictionRun")
                        .WithMany("Predictions")
                        .HasForeignKey("PredictionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravModel.Domain.Starter", "Starter")
                        .WithMany()
                        .HasForeignKey("StarterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredictionRun");

                    b.Navigation("Starter");
                });

            modelBuilder.Entity("TravModel.Domain.Meeting", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("TravModel.Domain.PredictionRun", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("TravModel.Domain.Race", b =>
                {
                    b.Navigation("BettingMarkets");

                    b.Navigation("Starters");
                });
#pragma warning restore 612, 618
        }
    }
}
